login:
  ip: localhost
  username: serveradmin
  password: password
  port: 9987
bot:
  name: UltimateTs
database:
  enable: false
  host: localhost
  name: databaseName
  user: root
  password: password
config:
  kickNotRegister: false
  defaultGroupId: 8
  assignWhenRegister: 0
perms:
  myPermission: 7
  group.admin: 2
  rank.admin: 2