main: ultimatets.UltimateTs
name: UltimateTs
author: DiscowZombie
version: 2.0.0
description: Interact and link groups with TeamSpeak.
website: https://www.spigotmc.org/resources/39076/
soft-depend: [PermissionsEx, zPermissions, Vault, LuckPerms]
commands:
   teamspeak:
     description: Main command
     aliases: ts
     usage: /<command> [link][unlink][status][broadcast][list]
permissions:
   ultimatets.*:
     description: Gives access to all UltimateTS commands
     default: op
     children:
       ultimatets.broadcast: true
       ultimatets.list.*: truee
   ultimatets.broadcast:
     description: Broadcast a message on TeamSpeak.
   ultimatets.list.*:
     description: View all players online on TeamSpeak and Minecraft.
     children:
       ultimatets.list.teamspeak: true
       ultimatets.list.minecraft: true
   ultimatets.list.teamspeak:
     description: View all players online on TeamSpeak.
   ultimatets.list.minecraft:
     description: View all players online on Minecraft.