main: ultimatets.UltimateTs
name: UltimateTs
author: DiscowZombie
version: 2.1.3
description: Interact and link groups with TeamSpeak.
website: https://www.spigotmc.org/resources/39076/
soft-depend: [PermissionsEx, zPermissions, LuckPerms, Vault]
commands:
   teamspeak:
     description: Main command
     aliases: ts
     usage: /<command> [ip][link][unlink][status][broadcast][list][update]
permissions:
   ultimatets.all:
     description: Gives access to all UltimateTS commands
     default: op
     children:
       ultimatets.broadcast: true
       ultimatets.list.all: true
       ultimatets.update: true
   ultimatets.broadcast:
     description: Broadcast a message on TeamSpeak.
   ultimatets.list.all:
     description: View all players online on TeamSpeak and Minecraft.
     children:
       ultimatets.list.teamspeak: true
       ultimatets.list.minecraft: true
   ultimatets.list.teamspeak:
     description: View all players online on TeamSpeak.
   ultimatets.list.minecraft:
     description: View all players online on Minecraft.
   ultimatets.update:
     description: Update player servers groups with new permissions.